### ISSUE TITLE
Remove `as qss` from all imports.

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/qiskit-superstaq#26]
Reason for this https://stackoverflow.com/a/46860500/5716192.

Basically, qiskit_superstaq hasn't earned the right popularity wise like numpy and pandas to use `as qss` yet.

**Comment by vtomole** [comment]
https://github.com/SupertechLabs/qiskit-superstaq/pull/138#discussion_r849659656

**Comment by richrines1** [comment]
fwiw i still have a (weak) preference for using `qiskit_superstaq` over `qss`; but if we aren't going to do this we should instead probably use `qss` everywhere? (right now we use a mix, e.g. `qiskit_superstaq` is still used in `compiler_output.py` and `serialization.py`)

**Comment by vtomole** [comment]
Okay. I'm totally down for a [Bike-shedding ](https://en.wikipedia.org/wiki/Law_of_triviality)session at the dev meeting about this.

**Comment by singular-value** [comment]
Edit: just saw @vtomole comment about having bike-shedding tomorrow, sounds good

---------------------------------------

Can we discuss more on why people prefer `qss` vs `qiskit_superstaq`?

For me, I prefer `qss` for the following reasons:
- less need for `from` imports since name is shorter. E.g., instead of `from qiskit_superstaq import import API_VERSION, ParallelGates` at top of a file, can just do `qss.API_VERSION` and `qss.ParallelGates`. This latter makes clear that these two vars are relevant to qss. See also this [tidbit in PEP8](https://peps.python.org/pep-0008/#:~:text=If%20this%20spelling,bar.yourclass.YourClass%E2%80%9D).
- A very concrete example would be in our server, where, for example, we have files that need both `css.ZZSwapGate` and `qss.ZZSwapGate`. In fairness, right now our code actually spells out `cirq_superstaq.ZZSwapGate` and `qiskit_superstaq.ZZSwapGate`, though I'd advocate for shortening it.
- discount this point until/unless I can prove it, but I actually did try to prototype closing out this issue a few months ago by having a bunch of `from qiskit_superstaq import ...` at tops of files. And I somehow ran into circular imports that didn't otherwise arise.

**Comment by vtomole** [comment]
Closed by vote.
